/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    skills: Skill;
    projects: Project;
    collaborators: Collaborator;
    'chat-messages': ChatMessage;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    skills: SkillsSelect<false> | SkillsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    collaborators: CollaboratorsSelect<false> | CollaboratorsSelect<true>;
    'chat-messages': ChatMessagesSelect<false> | ChatMessagesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-content': SiteContent;
  };
  globalsSelect: {
    'site-content': SiteContentSelect<false> | SiteContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  /**
   * Имя, которое отображается в интерфейсе и профиле.
   */
  displayName?: string | null;
  /**
   * Только главный администратор может создавать/удалять пользователей и назначать роли.
   */
  role: 'superadmin' | 'admin';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Короткое описание изображения для доступности (скринридеры) и SEO. Это не подпись на странице.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  /**
   * Например: services -> страница откроется по /services
   */
  slug: string;
  isPublished?: boolean | null;
  showInNavigation?: boolean | null;
  /**
   * Если пусто, используется "Название страницы".
   */
  navigationLabel?: string | null;
  /**
   * Графический редактор структуры страницы: добавляй/удаляй/перетаскивай блоки, чтобы собрать новую страницу.
   */
  blocks?:
    | (
        | {
            eyebrow?: string | null;
            title: string;
            description?: string | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            title?: string | null;
            content: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            title?: string | null;
            items?:
              | {
                  label: string;
                  url: string;
                  note?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'links';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills".
 */
export interface Skill {
  id: number;
  /**
   * Заголовок секции на странице портфолио.
   */
  title: string;
  /**
   * Служебный код категории (например: automation, blender).
   */
  slug: string;
  /**
   * Опционально: текст под заголовком категории в портфолио.
   */
  description?: string | null;
  /**
   * Если выключено, категория и проекты из нее скрываются на сайте.
   */
  isVisible?: boolean | null;
  /**
   * Чем меньше число, тем выше категория в списке.
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  /**
   * Короткий заголовок карточки.
   */
  title: string;
  /**
   * Показывается в нижней части карточки.
   */
  description: string;
  /**
   * Показывается в модальном окне карточки (опционально).
   */
  details?: string | null;
  /**
   * Фон карточки.
   */
  image?: (number | null) | Media;
  /**
   * Листаемая галерея в модальном окне (опционально).
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Категория из коллекции "Категории".
   */
  skill: number | Skill;
  /**
   * Бейдж на карточке проекта.
   */
  status: 'done' | 'wip' | 'placeholder';
  /**
   * Кнопки/ссылки проекта: GitHub, Telegram, сайт и т.д.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Быстро скрыть карточку с сайта без удаления.
   */
  isVisible?: boolean | null;
  /**
   * Чем меньше число, тем выше карточка в категории.
   */
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborators".
 */
export interface Collaborator {
  id: number;
  /**
   * Название карточки.
   */
  name: string;
  role: string;
  /**
   * Текст в карточке по умолчанию (нижняя 1/3 часть).
   */
  about: string;
  /**
   * Показывается в модальном окне карточки.
   */
  details?: string | null;
  /**
   * Фон карточки.
   */
  image?: (number | null) | Media;
  /**
   * Опциональная галерея в модальном окне.
   */
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Если заполнить, в карточке и модальном окне появится live Discord-профиль в стиле главной.
   */
  discordUserId?: string | null;
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  isVisible?: boolean | null;
  sort?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages".
 */
export interface ChatMessage {
  id: number;
  /**
   * Имя отправителя в live-чате.
   */
  name: string;
  /**
   * Содержимое сообщения. Можно редактировать в CMS.
   */
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'skills';
        value: number | Skill;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'collaborators';
        value: number | Collaborator;
      } | null)
    | ({
        relationTo: 'chat-messages';
        value: number | ChatMessage;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  displayName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  isPublished?: T;
  showInNavigation?: T;
  navigationLabel?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              description?: T;
              image?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              title?: T;
              content?: T;
              id?: T;
              blockName?: T;
            };
        links?:
          | T
          | {
              title?: T;
              items?:
                | T
                | {
                    label?: T;
                    url?: T;
                    note?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "skills_select".
 */
export interface SkillsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  isVisible?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  details?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  skill?: T;
  status?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  isVisible?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collaborators_select".
 */
export interface CollaboratorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  about?: T;
  details?: T;
  image?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  discordUserId?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  isVisible?: T;
  sort?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "chat-messages_select".
 */
export interface ChatMessagesSelect<T extends boolean = true> {
  name?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content".
 */
export interface SiteContent {
  id: number;
  /**
   * Логотип, название и базовое SEO-описание.
   */
  branding?: {
    /**
     * Используется в title вкладки и в шапке.
     */
    siteName?: string | null;
    /**
     * Краткое описание для мета-тегов.
     */
    siteDescription?: string | null;
    /**
     * Изображение логотипа в шапке (опционально).
     */
    logo?: (number | null) | Media;
    /**
     * Показывается, если нужен текстовый бренд в шапке.
     */
    logoText?: string | null;
  };
  /**
   * Глобальные цвета и стиль карточек/панелей.
   */
  design?: {
    /**
     * HEX-цвет, например #63b3ed.
     */
    accentColor?: string | null;
    /**
     * HEX-цвет начала фонового градиента.
     */
    backgroundFrom?: string | null;
    /**
     * HEX-цвет конца фонового градиента.
     */
    backgroundTo?: string | null;
    /**
     * Прозрачность стеклянных панелей.
     */
    glassOpacity?: number | null;
    panelRadius?: number | null;
  };
  /**
   * Правила отображения карточек проектов и друзей.
   */
  cardSettings?: {
    columnsDesktop?: number | null;
    columnsTablet?: number | null;
    columnsMobile?: number | null;
    showStatusBadge?: boolean | null;
    enableHoverExpand?: boolean | null;
  };
  navigation?: {
    /**
     * Пункты плавающей навигации в шапке.
     */
    items?:
      | {
          label: string;
          href: string;
          isVisible?: boolean | null;
          id?: string | null;
        }[]
      | null;
    donateLabel?: string | null;
    donateUrl?: string | null;
  };
  /**
   * Тексты и видимость блоков существующих страниц.
   */
  pages?: {
    home?: {
      isVisible?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      /**
       * Какой Discord-профиль показывать в блоке live-статуса.
       */
      discordUserId?: string | null;
      socialLinks?:
        | {
            icon: string;
            label: string;
            note: string;
            url: string;
            id?: string | null;
          }[]
        | null;
    };
    portfolio?: {
      isVisible?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      emptyCategoryDescription?: string | null;
    };
    friends?: {
      isVisible?: boolean | null;
      eyebrow?: string | null;
      title?: string | null;
      description?: string | null;
      emptyDescription?: string | null;
    };
    liveChat?: {
      isVisible?: boolean | null;
      title?: string | null;
    };
  };
  footer?: {
    copyright?: string | null;
    domainsText?: string | null;
    vertexpointUrl?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-content_select".
 */
export interface SiteContentSelect<T extends boolean = true> {
  branding?:
    | T
    | {
        siteName?: T;
        siteDescription?: T;
        logo?: T;
        logoText?: T;
      };
  design?:
    | T
    | {
        accentColor?: T;
        backgroundFrom?: T;
        backgroundTo?: T;
        glassOpacity?: T;
        panelRadius?: T;
      };
  cardSettings?:
    | T
    | {
        columnsDesktop?: T;
        columnsTablet?: T;
        columnsMobile?: T;
        showStatusBadge?: T;
        enableHoverExpand?: T;
      };
  navigation?:
    | T
    | {
        items?:
          | T
          | {
              label?: T;
              href?: T;
              isVisible?: T;
              id?: T;
            };
        donateLabel?: T;
        donateUrl?: T;
      };
  pages?:
    | T
    | {
        home?:
          | T
          | {
              isVisible?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              discordUserId?: T;
              socialLinks?:
                | T
                | {
                    icon?: T;
                    label?: T;
                    note?: T;
                    url?: T;
                    id?: T;
                  };
            };
        portfolio?:
          | T
          | {
              isVisible?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              emptyCategoryDescription?: T;
            };
        friends?:
          | T
          | {
              isVisible?: T;
              eyebrow?: T;
              title?: T;
              description?: T;
              emptyDescription?: T;
            };
        liveChat?:
          | T
          | {
              isVisible?: T;
              title?: T;
            };
      };
  footer?:
    | T
    | {
        copyright?: T;
        domainsText?: T;
        vertexpointUrl?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}